site_name: Spine Size 
author: Dilawar Singh <dilawars@ncbs.res.in>
site_author: Dilawar Singh <dilawars@ncbs.res.in>
copyright: 'Copyright &copy; 2016-2019 Dilawar Singh'
repo_url: https://github.com/dilawar/Hippo
theme:
    name: material
    highlightjs: true
    hljs_languages:
        - php
        - python

extra_css: [extra.css]

markdown_extensions:
    - admonition
    - toc
    - attr_list
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.arithmatex
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

plugins:
    - markdownextradata: {}

extra_javascript:
  # other extra java script
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
